# Databricks notebook source
# MAGIC %sql
# MAGIC truncate table ndh.actual_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC Insert into ndh.actual_ndt(KPI_TYPE_TEXT
# MAGIC ,SITE_ID
# MAGIC ,SITE_NAME
# MAGIC ,LEASE_ID
# MAGIC ,TRANSACTION_ID
# MAGIC ,COMPANY_CODE
# MAGIC ,CALENDAR_YEAR
# MAGIC ,CALENDAR_MONTH
# MAGIC ,LEASE_CLASSIFICATION_CODE
# MAGIC ,ACTUAL_LC_AMOUNT
# MAGIC ,ACTUAL_USD_AMOUNT
# MAGIC ,LEGALLY_COMMITTED_INDICATOR
# MAGIC ,LOCAL_CURRENCY_CODE
# MAGIC ,CREATE_DATE
# MAGIC ,UPDATE_DATE
# MAGIC ,LEASE_SITE_COUNT
# MAGIC ,COMMENTS_TEXT
# MAGIC ,POSTING_PERIOD
# MAGIC ,PROFIT_CENTER
# MAGIC ,G_L_ACCOUNT
# MAGIC ,ASSIGNMENT_CODE
# MAGIC ,FLOW_TYPE_CODE
# MAGIC ,DOCUMENT_TYPE_CODE
# MAGIC ,GROWTH_SUSTAIN_SPLIT_TEXT)
# MAGIC
# MAGIC select  KPI
# MAGIC ,SITE_ID
# MAGIC ,SITE_NAME
# MAGIC ,LEASE_ID
# MAGIC ,TRANSACTION_ID
# MAGIC ,COMPANY_CODE
# MAGIC ,YEAR
# MAGIC ,MONTH
# MAGIC ,LEASE_CLASSIFICATION
# MAGIC ,ACTUAL_AMOUNT
# MAGIC ,ACTUAL_AMOUNT_USD
# MAGIC ,LEGALLY_COMMITTED
# MAGIC ,LOCAL_CURRENCY
# MAGIC ,LOAD_DATE
# MAGIC ,UPDATE_DATE
# MAGIC ,NO_OF_LEASE_SITES
# MAGIC ,TEXT
# MAGIC ,POSTING_PERIOD
# MAGIC ,PROFIT_CENTER
# MAGIC ,G_L_ACCOUNT
# MAGIC ,ASSIGNMENT
# MAGIC ,FLOW_TYPE
# MAGIC ,DOCUMENT_TYPE
# MAGIC ,GROWTH_SUSTAIN_SPLIT_TEXT from ndh.refm_ac_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC truncate table ndh.le_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC insert into ndh.le_ndt
# MAGIC select KPI
# MAGIC ,LE_TYPE
# MAGIC ,SITE_ID
# MAGIC ,SITE_NAME
# MAGIC ,LEASE_ID
# MAGIC ,TRANSACTION_ID
# MAGIC ,COMPANY_CODE
# MAGIC ,VALUE_TYPE
# MAGIC ,YEAR
# MAGIC ,MONTH
# MAGIC ,LEASE_CLASSIFICATION
# MAGIC ,LE_AMOUNT
# MAGIC ,LE_AMOUNT_USD
# MAGIC ,LEGALLY_COMMITTED
# MAGIC ,LOCAL_CURRENCY
# MAGIC ,LOAD_DATE
# MAGIC ,UPDATE_DATE
# MAGIC ,NO_OF_LEASE_SITES
# MAGIC ,AUTO_RENEWAL_Y_N from ndh.refm_le_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC truncate table ndh.plan_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC Insert into ndh.plan_ndt(
# MAGIC KPI_TYPE_TEXT 
# MAGIC ,SITE_ID 
# MAGIC ,SITE_NAME 
# MAGIC ,LEASE_ID 
# MAGIC ,TRANSACTION_ID 
# MAGIC ,COMPANY_CODE 
# MAGIC ,VALUE_TYPE_CODE  
# MAGIC --,OP_PLAN_TYPE_CODE
# MAGIC ,CALENDAR_YEAR 
# MAGIC ,CALENDAR_MONTH 
# MAGIC ,LEASE_CLASSIFICATION_CODE 
# MAGIC ,PLAN_LC_AMOUNT 
# MAGIC ,PLAN_USD_AMOUNT 
# MAGIC ,LEGALLY_COMMITTED_INDICATOR 
# MAGIC ,LOCAL_CURRENCY_CODE 
# MAGIC ,CREATE_DATE 
# MAGIC ,UPDATE_DATE 
# MAGIC ,LEASE_SITE_COUNT 
# MAGIC ,AUTO_RENEWAL_INDICATOR)
# MAGIC  
# MAGIC select 
# MAGIC KPI 
# MAGIC ,SITE_ID 
# MAGIC ,SITE_NAME 
# MAGIC ,LEASE_ID 
# MAGIC ,TRANSACTION_ID 
# MAGIC ,COMPANY_CODE 
# MAGIC ,VALUE_TYPE 
# MAGIC ,YEAR 
# MAGIC ,MONTH 
# MAGIC ,LEASE_CLASSIFICATION 
# MAGIC ,PLAN_AMOUNT 
# MAGIC ,PLAN_AMOUNT_USD 
# MAGIC ,LEGALLY_COMMITTED 
# MAGIC ,LOCAL_CURRENCY 
# MAGIC ,LOAD_DATE 
# MAGIC ,UPDATE_DATE 
# MAGIC ,NO_OF_LEASE_SITES 
# MAGIC ,AUTO_RENEWAL_Y_N  from ndh.refm_pl_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC Insert into ndh.opex_le_ndt(COUNTRY_NAME
# MAGIC ,OPEX_LE_USD_AMOUNT
# MAGIC ,OPEX_LE_LC_AMOUNT
# MAGIC ,CALENDAR_YEAR
# MAGIC ,LOCAL_CURRENCY_CODE
# MAGIC ,LE_TYPE_CODE )
# MAGIC
# MAGIC select COUNTRY_NAME
# MAGIC ,OPEX_LE_AMOUNT_USD
# MAGIC ,OPEX_LE_AMOUNT
# MAGIC ,cast(YEAR as timestamp)
# MAGIC ,LOCAL_CURRENCY
# MAGIC ,LE_TYPE from ndh.refm_opex_le_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC Insert into ndh.opex_plan_ndt(GLOBAL_COST_ELEMENT
# MAGIC ,COUNTRY_CODE
# MAGIC ,SFS_LINE_ITEM
# MAGIC ,CALENDAR_MONTH
# MAGIC ,CALENDAR_YEAR
# MAGIC ,OPEX_PL_USD_AMOUNT
# MAGIC ,OPEX_PL_LC_AMOUNT)
# MAGIC
# MAGIC select GLOBAL_COST_ELEMENT
# MAGIC ,COMPANY_CODE
# MAGIC ,SFS_LINE_ITEM
# MAGIC ,MONTH
# MAGIC ,cast(YEAR as timestamp)
# MAGIC ,OPEX_PL_AMOUNT_USD
# MAGIC ,OPEX_PL_AMOUNT from ndh.refm_opex_pl_ndt

# COMMAND ----------

# MAGIC %sql
# MAGIC truncate table NDH.ACTUAL_NDA

# COMMAND ----------

ACTUAL_NDA_FINAL_DF=spark.sql('''select distinct KPI_TYPE_TEXT
,SITE_ID
,SITE_NAME
,LEASE_ID
--,TRANSACTION_ID
,COMPANY_CODE
,CALENDAR_YEAR
,CALENDAR_MONTH
,LEASE_CLASSIFICATION_CODE
,ACTUAL_LC_AMOUNT
,ACTUAL_USD_AMOUNT
,LEGALLY_COMMITTED_INDICATOR
,LOCAL_CURRENCY_CODE
--,CREATE_DATE
--,UPDATE_DATE
,LEASE_SITE_COUNT
,COMMENTS_TEXT
,POSTING_PERIOD
,PROFIT_CENTER
,G_L_ACCOUNT
--,ASSIGNMENT_CODE
,FLOW_TYPE_CODE
,DOCUMENT_TYPE_CODE
,GROWTH_SUSTAIN_SPLIT_TEXT
from ndh.actual_ndt where date(create_date) in ("2022-06-07","2022-06-09","2022-06-13","2022-06-20","2022-07-15","2022-08-12","2022-09-14","2022-10-14","2022-11-11","2022-12-16","2023-01-17","2023-01-30","2023-02-13","2023-03-13","2023-04-13","2023-05-11","2023-06-15","2023-07-13","2023-08-17","2023-09-13","2023-10-12","2023-11-13") and Flow_Type_Code in ('Q20','Q24') and PROFIT_CENTER in (800001,800002,800003,800004,800005,800006,800007)''').createOrReplaceTempView("ACTUAL_NDA_FINAL")

# COMMAND ----------

# MAGIC %sql
# MAGIC insert into NDH.ACTUAL_NDA
# MAGIC Select distinct KPI_TYPE_TEXT
# MAGIC ,SITE_ID
# MAGIC ,SITE_NAME
# MAGIC ,LEASE_ID
# MAGIC ,COMPANY_CODE
# MAGIC ,CALENDAR_YEAR
# MAGIC ,CALENDAR_MONTH
# MAGIC ,LEASE_CLASSIFICATION_CODE
# MAGIC ,ACTUAL_LC_AMOUNT
# MAGIC ,ACTUAL_USD_AMOUNT
# MAGIC ,LEGALLY_COMMITTED_INDICATOR
# MAGIC ,LOCAL_CURRENCY_CODE
# MAGIC --,CREATE_DATE
# MAGIC --,UPDATE_DATE
# MAGIC ,LEASE_SITE_COUNT
# MAGIC ,COMMENTS_TEXT
# MAGIC ,POSTING_PERIOD
# MAGIC ,PROFIT_CENTER
# MAGIC ,G_L_ACCOUNT
# MAGIC --,ASSIGNMENT_CODE
# MAGIC ,FLOW_TYPE_CODE
# MAGIC ,DOCUMENT_TYPE_CODE
# MAGIC ,GROWTH_SUSTAIN_SPLIT_TEXT from ACTUAL_NDA_FINAL

# COMMAND ----------

# MAGIC %sql
# MAGIC truncate table NDH.LE_NDA

# COMMAND ----------

# MAGIC %sql
# MAGIC insert into NDH.LE_NDA
# MAGIC select * from ndh.LE_NDT
